### ISSUE TITLE
Request: Bevel Change (Arc Miter)

### ISSUE THREAD

**Issue by torridgristle** [jayanam/jmesh-tools#1]
Inner Miter should either default to Arc or have an option to use Arc in the panel. It seems to always provide cleaner geometry and shading for corners due to spreading out the edges of the corner bevel rather than collecting them all into one vertex. Seems it only needs the line `bevel.miter_outer = 'MITER_ARC'` added to the fc_bevel_util.py code with the other bevel modifier info.

Also, boosting the segment count to 6 and setting the bevel profile to 0.5 seems to be the final segment count that noticeably makes beveled edges smoother before it hardly looks different at all, at least with the weighted normals modifier.

**Comment by jayanam** [comment]
MITER_ARC added, will test the other settings like 0.5 for profile
