### ISSUE TITLE
Feature request: Allow user to scale and/or offset the primitive 

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/jmesh-tools#11]
Currently, I can only move the individual points of a primitive. This is not accurate to give me a uniform offset from the original shape. (IINW the "move points" feature is not meant to scale the primitive in the first place.) 

If I can use **Scale** or **Offset** operation on the primitive, I get the chance to slice and step-change in the extrusion, etc.

For example, I draw a primitive circle of 1 cm dia, and extrude it through the target shape. Then I use **Difference**. Then I scale/offset the circle to 2 cm, and extrude it to 1 cm and again use **Difference**. 

The current workaround is to create these shapes outside the Addon, and then duplicate them, scale the duplicate, and then use both objects one by one on the target object.

**Comment by jayanam** [comment]
No, there is a reset option now so that you can start with the current
primitive from the same position after the first boolean operation. Just
right click after that and you can continue with the Primitive (e.g. circle
can be resized after reset, but Im still working on this feature, perhaps a
scale is the better option, will see)

**Comment by raindropsfromsky** [comment]
Just wondering: What will work better with a polyline, **Scale** or **Offset**? I guess the latter, especially if the polyline contains any internal angle >180 degrees.

Just my 2 cents...

**Comment by jayanam** [comment]
Well Im not sure if I provide this feature for poylyline cause it's hard to
determine the center, especially for complicated shapes. But I think of
adding the scale to rext and circle.

**Comment by jayanam** [comment]
Just added scale for circle to the latest version 1.2.2.1

**Comment by raindropsfromsky** [comment]
> Just added scale for circle to the latest version 1.2.2.1
That's fantastic! And since we can change the number of vertices in a circle, it should mean that all regular polygons are also covered, including the popular shapes: triangle, square, pentagon, hexagon, octagon. Right?

**Comment by jayanam** [comment]
Yes, exactly.
