### ISSUE TITLE
Feature: Gizmo

### ISSUE THREAD

**Issue by jayanam** [jayanam/jmesh-tools#13]
A gizmo should be added to the primitives so that these can be 

- moved after creation
- scaled after creation

**Comment by jayanam** [comment]
First version of Gizmo added for circle and rectangle, polyline is next

**Comment by raindropsfromsky** [comment]
What about Rotate?

**Comment by jayanam** [comment]
Currently I think about these features for the gizmo, scale and rotate.

**Comment by jayanam** [comment]
Will close this one, but will add a new issue for gizmo improvements
