### ISSUE TITLE
Suggestion: Replace the OSD with a panel with proper controls (e.g. drop-down menu)

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/jmesh-tools#15]
The OSD for primitives does not have consistent behavior:
1. Some of the keys change the option.
2. The others execute the command.

There is no indication which is which.

For example,
![image](https://user-images.githubusercontent.com/9047168/82721385-51f47400-9cda-11ea-8ead-2eb6d55b18a3.png)

P, O, M and C _change_ what is listed on the left.
But CTRL+Click and ESC execute the command listed on the left.

Then it is best to present the first four options as drop-down menu, and the last two as tooltip.

Just like the window that pops up in the left bottom corner when a circle is added in Blender:
![image](https://user-images.githubusercontent.com/9047168/82721804-78b4a980-9cde-11ea-9fda-bb3f6cac3493.png)

**Comment by 0z3l07** [comment]
Or a pie menu for fast switching of modes:)

**Comment by jayanam** [comment]
What do you mean by "switching modes" ?

**Comment by jayanam** [comment]
Closing this one cause this kind of popups is exactly what I dont want for the primtive mode:-)
