### ISSUE TITLE
Buglet: The circle primitive needs three optimizations

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/jmesh-tools#16]
There are three tiny problems in the OSD (on-screen display) for the **Circle** primitive:

1. In the first OSD, there is one issue: Instead of "Start", it should be "Click at center", because the user must start at the desired center of the circle by clicking there.
![image](https://user-images.githubusercontent.com/9047168/82722013-60458e80-9ce0-11ea-8867-8eb92c3a16af.png)<br><br>The OSD changes at this point to- 
![image](https://user-images.githubusercontent.com/9047168/82721971-1e1c4d00-9ce0-11ea-9601-79fc239081ff.png)
This display has two tiny issues:
2. If the user creates the circle, he cannot set segments. Therefore, the **Set segments** command should be listed BEFORE the **Create** command.

3. The creation of circle involves three steps, but the ESC key aborts the whole sequence, instead of undoing the sequence step-by-step. Therefore ESC can be best described as "Abort" (not "undo").

**Comment by jayanam** [comment]
2. and 3. fixed with 1.2.6.3. The first point I kept to "Start" for every primitive.
