### ISSUE TITLE
Suggestion: Move cutters into a different collection

### ISSUE THREAD

**Issue by 0z3l07** [jayanam/jmesh-tools#20]
Hi,

when you work non-destructively it would be cool if you could move cutters into a new collection to make it more clear and maybe rename them properly. And hide them by default :)
Just some inspiration I got from seeing boxcutter in action. 

Thx

**Comment by jayanam** [comment]
Hi, when you ay cutter, you mean different objects you use for i.e.
difference operations?

I dont know this feature of boxcutter and I also dont want to copy
boxcutter, but what is your requirement? You can always move objects to
collections and then hide the collection. How can Jmesh tools help with
that?

**Comment by 0z3l07** [comment]
Yeah cutter aka primitives I created with jmesh for non applied booleans. After you make a cut (difference) with a rectangle e.g (and you have the "apply immediately" box **not** checked) it would help to clean up the visual appearance of the "scene collection" if the rectangle would be moved into a "only boolean" collection. Hiding them would also keep the focus on your object you work on.

jmesh:
![jmesh](https://user-images.githubusercontent.com/24977832/83338233-70520500-a2c2-11ea-9bd1-41d93ae37d48.png)

bcutter:
![bcutter](https://user-images.githubusercontent.com/24977832/83338241-7f38b780-a2c2-11ea-8d43-6a909f147dd0.png)

That you dont want to copy boxcutter is totally understandable but this is only a logical step to streamline it a bit imho  :)

![jemsh2](https://user-images.githubusercontent.com/24977832/83338450-cde75100-a2c4-11ea-809a-94407dd5fc05.png)
This is after some non destructive operations. Iam just asking that jmesh could do some qol stuff like hiding bool objects and move them into a seperate collection.

thx for considering :)

**Comment by 0z3l07** [comment]
The booltool from blender has an "hide bool objects" button e.g
Maybe something like that

**Comment by jayanam** [comment]
Ah I see, thx for clarifying this, will take it into account.

**Comment by jayanam** [comment]
Ok, just added tis feature to 1.2.7.0, the name of the collection is **JM Bool Pending**:

![image](https://user-images.githubusercontent.com/18039584/83339964-4bb25900-a2d3-11ea-868c-4c4e9b7c4902.png)
