### ISSUE TITLE
Question/bug?!

### ISSUE THREAD

**Issue by 0z3l07** [jayanam/jmesh-tools#21]
Hi,

when I click "apply boolean" without having any bools active, it deletes my current selected object.
Is that a intended feature? The same for when I have bools (non applied) active, when I select my main object all the bools are still there but the selected object get deleted. I think I dont understand what the "apply boolean" button is for lol

Edit: The tooltip says "applies pending bool operators" 
From what I can tell it doesnt do that
It seems like to work like a delete selected button
"delete after apply" is active btw

**Comment by jayanam** [comment]
Thx for the info, will have a look

**Comment by 0z3l07** [comment]
If this is a error I believe "Apply all" should apply every bool object except the bevel and weighted normals. Or maybe that has to be tested in detail

**Comment by jayanam** [comment]
I added two new option:

* Apply selected booleans
* Apply all pending booleans
