### ISSUE TITLE
1.2.8.1 cant be activated

### ISSUE THREAD

**Issue by 0z3l07** [jayanam/jmesh-tools#22]
Hi,

sry for spamming the issues :(

> Modules Installed (jmesh-tools-master) from 'E:\\Blender_files\\Addons\\jmesh-tools-master1.2.8.1.zip' into 'C:\\Users\\ _username_ \\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'

1 click (activation)
> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 330, in enable
>     importlib.reload(mod)
>   File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\importlib\__init__.py", line 169, in reload
>     _bootstrap._exec(spec, module)
>   File "<frozen importlib._bootstrap>", line 630, in _exec
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "C:\Users\ _username_ \AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\jmesh-tools-master\__init__.py", line 37, in <module>
>     from . fc_apply_bool_op     import FC_ApplyBoolOperator, FC_ApplyAllBoolOperator
> ImportError: cannot import name 'FC_ApplyAllBoolOperator' from 'jmesh-tools-master.fc_apply_bool_op' (C:\Users\ _username_ \AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\jmesh-tools-master\fc_apply_bool_op.py)
> 
2 click (activation)
> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "C:\Users\ _username_ \AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\jmesh-tools-master\__init__.py", line 37, in <module>
>     from . fc_apply_bool_op     import FC_ApplyBoolOperator, FC_ApplyAllBoolOperator
> ImportError: cannot import name 'FC_ApplyAllBoolOperator' from 'jmesh-tools-master.fc_apply_bool_op' (C:\Users\ _username_ \AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\jmesh-tools-master\fc_apply_bool_op.py)
>

**Comment by jayanam** [comment]
Hm strange, it's all committed. Could you remove the old version first and
then install the new one?

**Comment by 0z3l07** [comment]
Iam so sorry......after restarting blender it worked 
Works like a charm, thx 
*embarrassed*
