### ISSUE TITLE
Issues with "apply all booleans"

### ISSUE THREAD

**Issue by 0z3l07** [jayanam/jmesh-tools#24]
v1.2.8.3

Hi,

I will try to update this issue with additional errors if I find it.

1.
I can reproduce this quite reliably but sometimes it works no problem. I have a feeling that this has something to do with ctrl+z when you undo things because of mistakes. But I had moments where this came up right from the start. I tried to look if it comes up when you use the same circle(blue outline) for all bools compared to you cancel(esc) after every bool and form a new one every time but cant seems to pin it down.
 
*Another thing I noticed is when you undo, your primitive overlay rewinds too as it seems.* That could be imagination tho edit: I pressed "snap to grid as it snapped back to polyline. Not quite reproducible. 

This was a fresh start of blender
> bpy.context.scene.apply_bool = False
> bpy.ops.machin3.view_axis(axis='FRONT')
> bpy.ops.mesh.primitive_cube_add(size=2, enter_editmode=False, location=(0, 0, 0))
> bpy.ops.object.fc_primitve_mode_op()
> bpy.context.space_data.context = 'MODIFIER'
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.modifier_apply(modifier="FC_BOOL")
> bpy.ops.object.modifier_apply(modifier="FC_BOOL.001")
> bpy.ops.object.apply_all_bool()
> Traceback (most recent call last):
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\jmesh-tools-master\fc_apply_bool_op.py", line 75, in execute
>     modifier.object.hide_set(False)
> AttributeError: 'NoneType' object has no attribute 'hide_set'
> 
> location: <unknown location>:-1

2. There is also an error I cant really reproduce consistently or at all

> Traceback (most recent call last):
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\jmesh-tools-master\fc_apply_bool_op.py", line 82, in execute
>     obj.select_set(True)
> RuntimeError: Error: Object 'Rect_Object' can't be selected because it is not in View Layer 'View Layer'!

This is prob a blender problem or user handling error

**Comment by 0z3l07** [comment]
Tested on 1.2.8.4

Seems to work when you have e.g only circles but when you add a different primitive in the mix the error stays (the hide-set one). 

Polyline on the left worked fine

Circle one the right gave the hide_set error

![error3](https://user-images.githubusercontent.com/24977832/83411047-c8e6e680-a417-11ea-86de-25c2eed2877f.png)



Cant really reproduce that :/

> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.modifier_apply(modifier="FC_BOOL")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.delete()
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.modifier_apply(modifier="FC_BOOL")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.delete()
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.modifier_apply(modifier="FC_BOOL")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.delete()
> bpy.context.scene.apply_bool = False
> bpy.context.scene.use_snapping = False
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.context.space_data.context = 'MODIFIER'
> bpy.ops.object.modifier_apply(modifier="FC_BOOL")
> bpy.ops.object.modifier_apply(modifier="FC_BOOL.001")
> bpy.ops.object.modifier_apply(modifier="FC_BOOL.002")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.apply_all_bool()
> Traceback (most recent call last):
>   File "C:\Users\horst\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\jmesh-tools-master\fc_apply_bool_op.py", line 84, in execute
>     obj.select_set(True)
> RuntimeError: Error: Object 'Circle_Object' can't be selected because it is not in View Layer 'View Layer'!
> 
> 
> location: <unknown location>:-1

![error2](https://user-images.githubusercontent.com/24977832/83410732-3ba39200-a417-11ea-88e7-97111514f9dd.png)

sry for giving you headaches :(

**Comment by 0z3l07** [comment]
Here I had 2 different ones in one object....no error but the rectangle bool wasnt deleted 
After undoing the steps it worked fine .......

![screen](https://user-images.githubusercontent.com/24977832/83411631-ebc5ca80-a418-11ea-957e-a3d35b949fd2.png)

**Comment by 0z3l07** [comment]
https://youtu.be/UZr74c4iRd8

https://youtu.be/Mu2Jl9XeCnQ

**Comment by jayanam** [comment]
Ok, this seems to be correct. Apply all booleans apply all pending booleans
for the selected target

**Comment by 0z3l07** [comment]
yeah but the polyline crashed too in the test 1 video

and in the 2, one of the circles didnt got deleted after beong applied and the hide-set error reappeard again

**Comment by jayanam** [comment]
I just tried the same with this Blender version:

![image](https://user-images.githubusercontent.com/18039584/83445776-e46ce400-a44d-11ea-97c6-aa35c7c8cdaf.png)

**Comment by 0z3l07** [comment]
I got the last 2.9 from the official site . may 31
I dont think you can get a earlier version

**Comment by jayanam** [comment]
Fixed with 1.2.8.5, new algorithm
