### ISSUE TITLE
Addon activation fails under Blender 2.83

### ISSUE THREAD

**Issue by wolfig** [jayanam/jmesh-tools#28]
Hi Jayanam,

I am working on a Macbook Pro (2017) and tried to install the JMESH addon but that fails:
1) downloaded ZIP from github
2) Blender 2.83 --> "Install" from ZIP (this works

When I try to activate the addon I get an error message:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/wgeithner/Library/Application Support/Blender/2.83/scripts/addons/jmesh-tools-master/__init__.py", line 37, in <module>
    from . fc_apply_bool_op     import FC_ApplyBoolOperator, FC_ApplyAllBoolOperator
ImportError: cannot import name 'FC_ApplyAllBoolOperator' from 'jmesh-tools-master.fc_apply_bool_op' (/Users/wgeithner/Library/Application Support/Blender/2.83/scripts/addons/jmesh-tools-master/fc_apply_bool_op.py)

Best regards
Wolfgang

**Comment by jayanam** [comment]
Hi, I dont know, I dont have a Mac, cant try it.

**Comment by 0z3l07** [comment]
I had that too I believe but on windows. After restarting blender I was able to activate it.
Try on 2.9 or 2.82 too. Get rid of old jmesh versions if you had them installed before in the addons folder.

**Comment by jayanam** [comment]
Ok, please try, could be an already installed and initialized version in
memory
