### ISSUE TITLE
Boolean modifiers should be added before the bevel modifiers

### ISSUE THREAD

**Issue by torridgristle** [jayanam/jmesh-tools#3]
Currently boolean modifiers are added after bevel modifiers and it breaks the visual of the mesh being worked on. It should be added before the bevel modifier, and weighted normal should it be added.

**Comment by jayanam** [comment]
Thx, have this on my list with improvements

**Comment by jayanam** [comment]
1.0.5.0 : Reassign sharp edges solves the problem after bool operation now.
