### ISSUE TITLE
Grammatical clarity suggestion, not really an issue

### ISSUE THREAD

**Issue by Hunanbean** [jayanam/jmesh-tools#30]
Hello and thank you again for what you have created shared with us. very useful tool sets.
I was reading the description of this project, and the way it was worded caused me to think that this was the older project
"Blender 2.8 / 2.9 mesh and hard surface utilities addon (before it was Fast Carve)"
If this was changed to 'Blender 2.8 / 2.9 mesh and hard surface utilities addon (previously known as Fast Carve)'
or 'Blender 2.8 / 2.9 mesh and hard surface utilities addon (formerly Fast Carve)'
Certainly not a terribly important issue, but i actually went and checked the dates on the Fast Carve project thinking that this was the project before Fast Carve, and that Fast Carve was the update. :)
Thanks again, and be well

**Comment by jayanam** [comment]
Yes, you are right, thx for pointing this out, I'm not a native speaker, German grammar is quite different in this case:-) Changed it.
