### ISSUE TITLE
Snap to hidden object. Not a target

### ISSUE THREAD

**Issue by ekkl** [jayanam/jmesh-tools#31]
New object are created on another object. (Not a target)
![Peek 2020-08-27 19-51](https://user-images.githubusercontent.com/5430541/91471451-cbce6780-e89e-11ea-9f96-43876bdf0953.gif)

**Comment by jayanam** [comment]
I guess it is not snapped to a hidden object but the object has non applied location, will check if I can reproduce

**Comment by jayanam** [comment]
@ekkl Please check if it still occurs with latest version of the addon.

**Comment by ekkl** [comment]
Thank's. All works properly.

**Comment by ekkl** [comment]
Same mistake again.
![Peek 2021-01-16 18-53](https://user-images.githubusercontent.com/5430541/104817798-3cfdbf80-582c-11eb-80af-f6fe0a7b0f1e.gif)
