### ISSUE TITLE
Stack Traces while in Primitve mode

### ISSUE THREAD

**Issue by HarDevSan** [jayanam/jmesh-tools#4]
V 1.0.2.8

After pressing "Primitve Mode", while editing my curve, there will be a trace back when I : 

* disable proportional editing  
* select anything in the hirarchy 
* click on anything in the curve options (Curve resolution etc.) 

See Videos here:

https://www.dropbox.com/sh/kppqpe0g0leqtrz/AAATqX1VN4TIOKqdQNM8yaVVa?dl=0

**Comment by jayanam** [comment]
Thx for adding the issue, which Blender version is used. I can't reproduce with 2.82 which is the current release and the addon doesn't support older versions than current release. Can you please try if you can repro with 2.82?

**Comment by HarDevSan** [comment]
Oh, forgot to provide the Blender version. I am using 2.81 right now. Glad to hear it should work with 2.82. 

I will report back and attach a blend in case I still have this issue with Blender 2.82. If not, I will try to remember to close this issue. 

Not sure when I am upgrading though, as I am in the middle of a project and have little time. 
Thx for having a look.

**Comment by HarDevSan** [comment]
Just found a workaround in this second as I started working :P 

In case anyone else run into this using 2.81:

Just hit escape to turn off Primitve mode before you edit your curve and you won't have any Stack Traces and won't need to retat the blend file for the "Primitve Mode" option to be available again.

**Comment by jayanam** [comment]
@HarDevSan  Could reproduce and uploaded a new version 1.0.3.0. New feature for curves added as well: Multiple points input. Ctrl + Click to start, then add new point by clicking, Ctrl + Click to finish. Ceated many curves like this, convert them all to mesh and then remesh to sculpt on these.

**Comment by HarDevSan** [comment]
GreaT! Thanks for the fix. That sounds like a great addition and will speed up the curve workflow even more. Looking forward. Thanks a Ton! Keep rocking.
