### ISSUE TITLE
Feature request - architectural  window

### ISSUE THREAD

**Issue by don570** [jayanam/jmesh-tools#42]
Feature request

Click  button  in  jmesh panel  to create a architectural  window ie house  window  at the
3d cursor position  in  either  X,Y or  viewport direction

Here are  some videos I made  while  practicing  the technique.
[method 1 video]https://drive.google.com/file/d/12903pTxLv6pksa6DITWQfBdX78PZNaen/view?usp=sharing)
[method 2]https://drive.google.com/file/d/1QHkHq7w-4FZUH4rs4jPBua_zWxQYIVuW/view?usp=sharing
[method 3]https://drive.google.com/file/d/1NFM4MKLxnhwi5YHKDLMmMDvvQY4bCwIB/view?usp=sharing

**Comment by jayanam** [comment]
The feature is too specific and fits more to an architecture addon.
