### ISSUE TITLE
Symmetrize only selected face/edge possible?

### ISSUE THREAD

**Issue by 0z3l07** [jayanam/jmesh-tools#44]
Since you introduced a symmetrize gizmo would it be possible to symmetrize also only selected geo in edit mode like for example you want an antenna on the other side but dont want the surrounding geo. The hp config symmetrize pie does that while holding ctrl for example.

**Comment by jayanam** [comment]
Yes, will do, we can implement it together tomorrow in the live stream:-)

**Comment by 0z3l07** [comment]
That would be cool I think
It was 16:00, right?

**Comment by jayanam** [comment]
Yes, here is the link:
https://youtu.be/toe3EUF4Viw

Will see if we can make it work then... haha.

**Comment by jayanam** [comment]
Ok, fixed in the live stream:-)
