### ISSUE TITLE
Array in a negative direction

### ISSUE THREAD

**Issue by Kivinay** [jayanam/jmesh-tools#45]
Hi, can you set up a way to either enter a negative value in the text bar for the 'JMesh array' or be able to scroll on the mouse wheel to select a distance (both positive and negative value)?
Thank you!

**Comment by jayanam** [comment]
Ok, will be added :-)

**Comment by jayanam** [comment]
Negative values can be entered now, for the mouse interaction I need a separate issue

**Comment by Kivinay** [comment]
Wow, sweet... and quick! Thank you, sir! Shall create a separate issue for the mouse interaction. Hope many people benefit from these as I don't want to give you extra work that not many people care about... But thanks again!

**Comment by jayanam** [comment]
Thx, yes, please add the issue, then I can think about a design and Im
sure it would be a great improvement, also for the widget library.
