### ISSUE TITLE
Bevel button incompatible --> mirror modifier with mirror object

### ISSUE THREAD

**Issue by don570** [jayanam/jmesh-tools#5]
Issue with  jmesh-tools  version 1.0.4.0  and earlier:
I can make mirror  modifier go nuts   by the following....
1)  start with cube  
2) create a cylinder nearby
3) select the cube and  make a mirror  modifier  using the  cylinder in middle
i.e. the cylinder is ticked as the  mirror object   (see image for result  of the  mirroring)
The image  shows mirroring about y axis  but  I could  have  chosen x-axis as well.
![screenshot-bevel-problem](https://user-images.githubusercontent.com/19693002/75120120-de998280-5656-11ea-8342-dcf0b1861476.png)

4)  select the cylinder and click on  'Bevel' button that jmesh supplies.
5)  the second cube disappears

**Comment by jayanam** [comment]
Thx for the input, and I found it: The bevel button set the pivot point of
the object to the center - what it shouldnt. Will be fixed

**Comment by jayanam** [comment]
Ok, is fixed in 1.0.4.1

**Comment by don570** [comment]
version  1.0.4.1  worked in blender  2.8.2  -  Good!

However I noticed  that even  though  I  clicked  'Remove'  button in  addon preferences  to
remove the  old version,   installing  the   new version  required  a bootup of linux
to get it to install fully  (perhaps  there was  residual code in  memory ???)

**Comment by jayanam** [comment]
Might be, but this sounds more like a Blender issue, which is still under
development in these experimental versions.
