### ISSUE TITLE
Spelling  error

### ISSUE THREAD

**Issue by don570** [jayanam/jmesh-tools#52]
Noticed  a spelling  error in  version   1.9.0.1
Thickness is correct spelling...

![screenshot-jmesh-spelling](https://user-images.githubusercontent.com/19693002/114085933-0316e500-9880-11eb-94a9-8fa5b6ef3a58.png)

Everything  working  well  so  far... 
Circular  array  undo  works !!!!

**Comment by jayanam** [comment]
Ok, fixed it in 1.9.0.2
