### ISSUE TITLE
I have a request for JMesh Tool. 

### ISSUE THREAD

**Issue by Bundy2021** [jayanam/jmesh-tools#57]
Hi. I send you Email Yesterday. Thanks for your fast Reply

Look this is the Boolean Modifier from Blender
<img width="379" alt="2021-07-27 20_14_07-Mail" src="https://user-images.githubusercontent.com/88054686/127208448-06adba3d-114c-4910-8545-805e96d96a93.png">

And there is the solver Option for "Self" and "Hole Tolerant"
<img width="116" alt="2021-07-27 20_15_19-Blender_  C__Users_Maximus-Prime_Documents_Blender (Neu)_New Begin 242_266_Bolze" src="https://user-images.githubusercontent.com/88054686/127208922-a41eaf1c-6fb7-442b-8a67-727c89917686.png">

When you Active this - Blender do a special algorithm for Boolean Operation. Take more Time but sometimes help about self intersection and other problems with Boolean.

Can you please bring this Option in your Tool. Like in the Picture 
![2021-07-27 20_43_00-Blender_  C__Users_Maximus-Prime_Documents_Blender (Neu)_New Begin 242_266_Bolze1](https://user-images.githubusercontent.com/88054686/127211041-c4d2779d-2416-4eca-a428-77ed132126e8.png)
I don't know how much work this is for you. Sorry when i want too much. Your JMesh Tool is also a very very good Tool for me and many People too.

Have a good Time.

Happy Blender

**Comment by jayanam** [comment]
Ok, feature added and uploaded to blendermarket & gumroad as well.
