### ISSUE TITLE
Jmesh-tools error

### ISSUE THREAD

**Issue by SmithMarkG** [jayanam/jmesh-tools#6]
Jayanam

I receive the following error when enabling JMesh Tools, would you know what could be causing the error:

ERROR (rna.define): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\makesrna\intern\rna_define.c:1840 RNA_def_property_enum_items: "Prefs.center_type", enum identifiers must not contain spaces.

I'am using blender 2.83 the latest experimental build.

Thank you
Mark

**Comment by jayanam** [comment]
Space removed from center_type enum
