### ISSUE TITLE
Suggestion - boolean operation - auto smooth

### ISSUE THREAD

**Issue by don570** [jayanam/jmesh-tools#60]
jmesh version 1.9.3.2
Blender 3.0 stable  - linux

I am testing  jmesh and so far it is very good,  but I noticed  some  poor shading  after trying a boolean 'difference' operation  in jmesh panel .   'Auto smooth'  makes  the  shading nice. Could it be built into jmesh???

Procedure....

1)  Begin with cube and put bevel modifier on it
2)  Create  a sphere to cut  into  cube
3)  use jmesh  for  boolean difference operation  -  target is the cube  with  bevel
4)  notice  the  shading in  result
5) Turn on 'auto smooth' option  for better shading

I recorded the screen if you  are interested in watching....
https://drive.google.com/file/d/1sry4DLSsmS2_UKWGgG33j2j5UI0HbET3/view?usp=sharing
___________________________________________________

**Comment by jayanam** [comment]
Hi,

JMesh has an own Bevel Operator that enables autosmooth

[image: image.png]

Best
Jay

**Comment by don570** [comment]
I was referring to situations where  jmesh  is not used for bevel operation.

I just wanted to inform you  of possible issues.  Thanks for jmesh.
Don
