### ISSUE TITLE
The On-Screen-Display (OSD) for primitives spills out of 3D viewport

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/jmesh-tools#8]
The On-Screen-Display (OSD) for primitives spills out of 3D viewport, as shown by the following screenshot.

![image](https://user-images.githubusercontent.com/9047168/82465251-b518b780-9adc-11ea-812a-b3948dc0af30.png)

Reporting for JMeshTools 1.2.0.0 running in Blender 2.90 Alpha.

**Comment by jayanam** [comment]
Fixed by showing the Input-method of Polyline only when shape is not created
