### ISSUE TITLE
The Polyline section offers Boolean operation too early in the workflow; creates confusion

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/jmesh-tools#9]
The polyline workflow is as follows:
1. Select a polyline
2. Draw it.
3. Adjust the shape (fine-tuning)
3. Extrude it (the extruded shape can be either inside the target shape or outside it).
4. Execute a Boolean operation between the polyline extrusion and the target shape.

So the on-screen display (OSD) should show only the relevant steps at each step. 
But as the following screenshot shows, the OSD shows Boolean operation right from start.

![image](https://user-images.githubusercontent.com/9047168/82466229-c31b0800-9add-11ea-9caf-ea55a44d06db.png)

This confuses the user. 

**Desired:**
The "Boolean" control should appear only AFTER the polyline is extruded.

In fact, there is no need for separate controls for the Boolean operations, as the top section of the JMeshTools Addon already has a nice panel for Boolean operations. The Booleans with Polyline can be handled with that section.

**Comment by jayanam** [comment]
No, because you can also execute a bool operation without extruding the shape, then it right cuts through the object when it is set to difference. Then you could reset the shape after cutting, switch to slice then and use the same shape with a different size to slice.

**Comment by raindropsfromsky** [comment]
Well, the property of a shape cutting "right through" when not extruded is counterintuitive, because when it is extruded, the 3D shape interacts with the target shape. 

So, when it is NOT extruded, we have only a **planar object** that is snapped to the surface of the target shape. So, logically speaking, if I draw a shape on a cube, and use **Difference** boolean operation, I expect the shape to cut a hole only in the face on which the primitive is snapped. 

But I also agree that it is useful to cut through the shape in one step.

So, on the whole, can we have an explicit tip "when not extruded, the primitive cuts through the shape".

BTW the addon has changed so much that it needs a new tutorial, explaining all the new powerful features and Easter eggs like this.

**Comment by jayanam** [comment]
Yes, will think about this. The video is in the making:-)

**Comment by jayanam** [comment]
I reopened this issue again for discussion.

**Comment by jayanam** [comment]
I decided to keep the one-click solution cause it is something that users do often and then dont want to extrude all the time. When I introduce the addon pref options, I will add it as an option then.
